@echo off
echo Automatically using portable Node.js...
set PATH=%~dp0node\node-v20.11.1-win-x64;%PATH%
echo Running NPM Install...
call npm install
echo Starting Backend Server...
start "Backend Server" /B node server.js
echo Starting Application...
npm run dev
pause